Revert "More blacklists in the account-app"
This reverts commit 6e25d00d9541d791cd2561832cc999892bf597ee.

Turns out the latest build of the account-app doesn't bootstrap properly. Bah
humbug

	2017-02-13 17:38:47.881:INFO::main: Logging initialized @665ms to org.eclipse.jetty.util.log.StdErrLog
	2017-02-13 17:38:48.164:INFO:oejs.SetUIDListener:main: Setting umask=02
	2017-02-13 17:38:48.186:INFO:oejs.SetUIDListener:main: Opened ServerConnector@1d057a39{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
	2017-02-13 17:38:48.186:INFO:oejs.SetUIDListener:main: Setting GID=999
	2017-02-13 17:38:48.187:INFO:oejs.SetUIDListener:main: Setting UID=999
	2017-02-13 17:38:48.192:INFO:oejs.Server:main: jetty-9.4.1.v20170120
	2017-02-13 17:38:48.211:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 1
	2017-02-13 17:38:51.608:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=2671ms
	2017-02-13 17:38:51.609:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@370736d9{/,file:///tmp/jetty-0.0.0.0-8080-ROOT.war-_-any-5269362348514142486.dir/webapp/,UNAVAILABLE}{/ROOT.war}
	java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///tmp/jetty-0.0.0.0-8080-ROOT.war-_-any-5269362348514142486.dir/webapp/WEB-INF/lib/javax.json-1.1.0-M1.jar
		at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:891)
		at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:837)
		at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159)
		at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:464)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
		at java.lang.Thread.run(Thread.java:745)
	Caused by:
	java.lang.IllegalArgumentException
		at org.objectweb.asm.ClassReader.<init>(Unknown Source)
		at org.objectweb.asm.ClassReader.<init>(Unknown Source)
		at org.objectweb.asm.ClassReader.<init>(Unknown Source)
		at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:959)
		at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:940)
		at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:887)
		at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:837)
		at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159)
		at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:464)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
		at java.lang.Thread.run(Thread.java:745)
	2017-02-13 17:38:51.636:INFO:oejs.AbstractConnector:main: Started ServerConnector@1d057a39{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
	2017-02-13 17:38:51.637:INFO:oejs.Server:main: Started @4421ms