Turns out the pe-mcollective resource is already declared =_=
This is so incredibly tedious.

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER:
    Duplicate declaration: Service[pe-mcollective] is already declared in file
    /etc/puppetlabs/puppet/environments/staging/dist/profile/manifests/puppetmaster.pp:71;
    cannot redeclare at
    /opt/puppet/share/puppet/modules/puppet_enterprise/manifests/mcollective/service.pp:6
    on node jenkins-puppet.osuosl.org
    Warning: Not using cache on failed catalog
    Error: Could not retrieve catalog; skipping run