Ensure that Class[Letsencrypt] is in the catalogue for the account app
Turns out this was previously being pulled in by profile::staticsite and I
could not get the catalogue compilation error below to reproduce in the testing
environment unless I explicitly tested the expectation in rspec-puppet

    Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Invalid relationship: Exec[letsencrypt certonly accounts.jenkins.io] { require => Class[Letsencrypt] }, because Class[Letsencrypt] doesn't seem to be in the catalog","issue_kind":"RUNTIME_ERROR","stacktrace":["Warning: The 'stacktrace' property is deprecated and will be removed in a future version of Puppet. For security reasons, stacktraces are not returned with Puppet HTTP Error responses."]}
    Warning: Not using cache on failed catalog
    Error: Could not retrieve catalog; skipping run